apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod-monitoring-platform
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/prod-monitoring/platform/identities
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
