apiVersion: v1
kind: Service
metadata:
  name: mimir-internal-lb
  namespace: mimir
  annotations:
    networking.gke.io/load-balancer-type: "Internal"

spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.0.14
  externalTrafficPolicy: Cluster

  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: mimir
    app.kubernetes.io/name: mimir

  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
