apiVersion: v1
kind: Service
metadata:
  name: tempo-internal-lb
  namespace: tempo
  annotations:
    networking.gke.io/load-balancer-type: "Internal"

spec:
  type: LoadBalancer
  loadBalancerIP: 10.40.0.13
  externalTrafficPolicy: Cluster

  selector:
    app.kubernetes.io/component: distributor
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo

  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP

    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
