apiVersion: v1
kind: Namespace
metadata:
  name: mimir
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: v1
kind: Namespace
metadata:
  name: tempo
---
apiVersion: v1
kind: Namespace
metadata:
  name: pyroscope

