apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
  namespace: mimir
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  namespace: loki
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo
  namespace: tempo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pyroscope
  namespace: pyroscope
