extraConfigmapMounts:
  - name: grafana-alert-rules
    configMap: grafana-alert-rules
    mountPath: /etc/grafana/provisioning/alerting/rules.yaml
    subPath: rules.yaml
    readOnly: true

dashboardsConfigMaps:
  observability: grafana-observability-dashboards

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1

    providers:
      - name: observability
        orgId: 1
        folder: Observability Lab
        type: file
        disableDeletion: true
        editable: false

        options:
          path: /var/lib/grafana/dashboards/observability

persistence:
  enabled: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    memory: 512Mi

service:
  type: ClusterIP

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Mimir
        uid: mimir
        type: prometheus
        access: proxy
        url: http://mimir.observability.svc.cluster.local:9009/prometheus
        isDefault: true
        editable: false

      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100
        editable: false

      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
        editable: false

      - name: Pyroscope
        uid: pyroscope
        type: grafana-pyroscope-datasource
        access: proxy
        url: http://pyroscope.observability.svc.cluster.local:4040
        editable: false

        jsonData:
          minStep: "15s"

grafana.ini:
  analytics:
    reporting_enabled: false
    check_for_updates: false

  users:
    allow_sign_up: false

  log:
    mode: console
    level: info
