apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  timeout: 15m
  install:
    remediation:
      retries: 2
  chart:
    spec:
      chart: grafana
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: grafana-community
        namespace: flux-system

  values:
    replicas: 1
    deploymentStrategy:
      type: Recreate  
    persistence:
      enabled: true
      storageClassName: standard-rwo
      size: 10Gi

    service:
      type: ClusterIP

    nodeSelector:
      workload: observability
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    datasources:
      datasources.yaml:
        apiVersion: 1

        datasources:
          - name: Mimir
            uid: mimir
            type: prometheus
            access: proxy
            url: http://mimir-gateway.mimir.svc.cluster.local/prometheus
            isDefault: true

          - name: Loki
            uid: loki
            type: loki
            access: proxy
            url: http://loki-gateway.loki.svc.cluster.local
            jsonData:
              httpHeaderName1: X-Scope-OrgID
              derivedFields:
                - name: trace_id
                  matcherType: label
                  matcherRegex: trace_id
                  datasourceUid: tempo
                  url: '$${__value.raw}'
                  urlDisplayLabel: "View Trace"
            secureJsonData:
              httpHeaderValue1: prod-app-a

          - name: Tempo
            uid: tempo
            type: tempo
            access: proxy
            url: http://tempo-gateway.tempo.svc.cluster.local

            jsonData:
              tracesToLogsV2:
                datasourceUid: loki
                spanStartTimeShift: "-1m"
                spanEndTimeShift: "1m"
                tags:
                  - key: service.name
                    value: service_name

                customQuery: true
                query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'

              tracesToMetrics:
                datasourceUid: mimir
                spanStartTimeShift: "-2m"
                spanEndTimeShift: "2m"

                queries:
                  - name: "Request rate"
                    query: 'sum(rate(http_server_request_duration_count{job="$${__span.tags["service.namespace"]}/$${__span.tags["service.name"]}"}[5m]))'

          - name: Pyroscope
            uid: pyroscope
            type: grafana-pyroscope-datasource
            access: proxy
            url: http://pyroscope-query-frontend.pyroscope.svc.cluster.local:4040