default:
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: alloy.observability.svc.cluster.local

grafana:
  enabled: false

prometheus:
  enabled: false

jaeger:
  enabled: false

opensearch:
  enabled: false

opentelemetry-collector:
  enabled: false

